# Generated by Django 3.2.5 on 2021-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs.', 'Mrs'), ('Ms', 'Ms')], max_length=19)),
                ('FirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('Phone', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
